version: "3.3"
services:
  database:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./.database_data:/var/lib/postgresql/data
      - ./db/structure.sql:/docker-entrypoint-initdb.d/structure.sql
    environment:
      - POSTGRES_USER=${MEMORY_TEST_DATABASE_USER}
      - POSTGRES_PASSWORD=${MEMORY_TEST_DATABASE_PWD}
      - POSTGRES_DB=${MEMORY_TEST_DATABASE}

  backend:
    build:
      context: ./back
    volumes:
      - ./back:/app
    working_dir: /app
    command: yarn dev
    environment:
      - MEMORY_TEST_DATABASE_USER=${MEMORY_TEST_DATABASE_USER}
      - MEMORY_TEST_DATABASE_PWD=${MEMORY_TEST_DATABASE_PWD}
      - MEMORY_TEST_DATABASE_URL=postgresql://database:5432/${MEMORY_TEST_DATABASE}
    ports:
      - 3000:3000
    depends_on:
      - database

  frontend:
    build:
      context: ./front
    ports:
      - 4200:4200
    command: yarn start
    volumes:
      - ./front:/app
    depends_on:
      - backend
